# Generated by Django 4.1.5 on 2023-01-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='section1',
            new_name='intro',
        ),
    ]
